[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy",
    "pandas",
    "scikit-learn",
    "tqdm",
    "tensorflow",
    "keras==2.4.3"
]
build-backend = "setuptools.build_meta"
